
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 06 18:17:27 CET 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 48;
  public static final int DIVIDE = 41;
  public static final int LBRACKET = 7;
  public static final int CONST = 18;
  public static final int EQUALS = 11;
  public static final int LOWER = 33;
  public static final int LPAREN = 5;
  public static final int GREATER = 32;
  public static final int CONTINUE = 24;
  public static final int NUM_CONST = 47;
  public static final int MINUS = 37;
  public static final int FOR = 22;
  public static final int STATIC = 9;
  public static final int RPAREN = 6;
  public static final int AND = 25;
  public static final int OR = 26;
  public static final int COMMA = 27;
  public static final int CLASS = 17;
  public static final int INC = 19;
  public static final int PLUS_EQUAL = 38;
  public static final int MINUS_EQUAL = 39;
  public static final int PLUS = 36;
  public static final int IF = 21;
  public static final int IS_EQUAL = 30;
  public static final int DOT = 28;
  public static final int IS_NOT_EQUAL = 31;
  public static final int EOF = 0;
  public static final int DIVIDE_EQUAL = 44;
  public static final int RETURN = 16;
  public static final int RBRACKET = 8;
  public static final int GREATER_EQUAL = 34;
  public static final int NEW = 13;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int SEMI_COLON = 12;
  public static final int IDENT = 50;
  public static final int BREAK = 29;
  public static final int VOID = 10;
  public static final int MODULE = 42;
  public static final int TIMES = 40;
  public static final int ELSE = 46;
  public static final int LBRACE = 3;
  public static final int READ = 15;
  public static final int TIMES_EQUAL = 43;
  public static final int RBRACE = 4;
  public static final int LOWER_EQUAL = 35;
  public static final int EXTENDS = 23;
  public static final int BOOL_CONST = 49;
  public static final int DEC = 20;
  public static final int PRINT = 14;
  public static final int MODULE_EQUAL = 45;
}

